import json
import sqlite3

def build_database():
    # Connect to SQLite database (creates songs.db if it doesn't exist)
    conn = sqlite3.connect('songs.db')
    cursor = conn.cursor()

    # Create the songs table
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS songs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            movie TEXT,
            trackName TEXT,
            musicDirector TEXT,
            singers TEXT,
            cast TEXT,
            album TEXT,
            releaseYear TEXT,
            coverArt TEXT
        )
    ''')
    
    # Clear old records if re-building
    cursor.execute('DELETE FROM songs')

    # Load the local fixed dataset generated by Node.js
    try:
        with open('songs-fixed.json', 'r', encoding='utf-8') as f:
            dataset = json.load(f)
    except FileNotFoundError:
        print("❌ Error: 'songs-fixed.json' not found. Run 'node generate-dataset.js' first.")
        return

    print(f"Loading {len(dataset)} tracks into the database...")

    for item in dataset:
        # Convert cast array to a comma-separated string if needed
        cast_data = item.get('cast', [])
        cast_str = ", ".join(cast_data) if isinstance(cast_data, list) else str(cast_data)
        
        cursor.execute('''
            INSERT INTO songs (movie, trackName, musicDirector, singers, cast, album, releaseYear, coverArt)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        ''', (
            item.get('movie'),
            item.get('trackName'),
            item.get('musicDirector'),
            item.get('singers'),
            cast_str,
            item.get('album'),
            str(item.get('releaseYear')),
            item.get('coverArt')
        ))

    conn.commit()
    conn.close()
    print("🎉 Database built successfully from songs-fixed.json!")

if __name__ == '__main__':
    build_database()